---
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: Kit BASH
author: "@vbem"
description: General kit functions to improve user experience of bash `run` steps
branding: { icon: terminal, color: green }

inputs: {}

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-composite-actions
outputs:
  entrypoint:
    description: 'Path to "kit.bash" entrypoint'
    value: ${{ steps.main.outputs.entrypoint }}
  source:
    description: 'Command to source "kit.bash" entrypoint in current shell'
    value: source ${{ steps.main.outputs.entrypoint }}

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions
runs:
  using: composite
  steps:
    - id: main
      shell: bash
      run: echo "entrypoint=${{ github.action_path }}/src/entrypoint.bash" >> "$GITHUB_OUTPUT"
